### ISSUE TITLE
For `migadu_identity` password_use `custom` is not working

### ISSUE THREAD

**Issue by ajgon** [metio/terraform-provider-migadu#152]
I'm opening another issue, to avoid polluting the old one :)

When I try to do `password_use: "custom"` I'm getting following error:

```
Attribute password_use value must be one of: ["none" "mailbox"], got: "custom"
```

also, despite of setting `password` attr, I'm getting

```
Attribute "password" must be specified when "password_use" is specified
```

but I'm not sure if it's related :).

**Comment by sebhoss** [comment]
Hi thanks again for taking your time to reach out & sorry this is still not working for you.

I'm kinda guessing that you are still running an older version of the provider? Maybe something you compiled locally even? There are multiple tests that cover exactly what you are trying to do and I can create identities with a custom password just fine using my own Migadu account. If are using the latest version, can you make sure that your configuration looks similar to what the integration test defines in https://github.com/metio/terraform-provider-migadu/blob/main/terratest/resources/migadu_identity/custom/resource.tf or paste your config here?

That said, I could improve this provider thanks again by adding tofu based tests in #154 and I noticed that the `name` attribute was always set in my tests, but neither required nor documented as such, however the Migadu API actually requires a name for every identity (#153).

**Comment by sebhoss** [comment]
Version [2024.2.13](https://github.com/metio/terraform-provider-migadu/releases/tag/2024.2.13) contains that change for the name attribute and the related [documentation](https://registry.terraform.io/providers/metio/migadu/latest/docs/resources/identity) change.

**Comment by ajgon** [comment]
Okay, sorry it was mistake in my files. I was mislead by this message `Attribute password_use value must be one of: ["none" "mailbox"], got: "custom"` - I thought "custom" was invalid value, when in fact it was invalid, BUT because password was empty (my mistake). So everything works as expected.

I'm not sure if it's possible to customize this message, but maybe something like `When password is not set, attribute password_use value must be one of: ["none" "mailbox"], got: "custom"` will be more descriptive. If not, then it is what it is :)

Thanks for checking this out for me, and sorry for the confusion!

**Comment by sebhoss** [comment]
Don't worry & thanks for the feedback! 

This message is produces with a configuration like this which is missing a value for the `password` attribute:

```hcl
resource "migadu_identity" "test" {
  domain_name  = "example.com"
  local_part   = "test"
  identity     = "other"
  name         = "Some Name"
  password_use = "custom"
}
```

and the output is:

```
╷
│ Error: Invalid Attribute Value Match
│ 
│   with migadu_identity.none,
│   on identities.tf line 13, in resource "migadu_identity" "test":
│   13:   password_use = "custom"
│ 
│ Attribute password_use value must be one of: ["none" "mailbox"], got: "custom"
╵
╷
│ Error: Invalid Attribute Combination
│ 
│   with migadu_identity.none,
│   on identities.tf line 13, in resource "migadu_identity" "test":
│   13:   password_use = "custom"
│ 
│ Attribute "password" must be specified when "password_use" is specified
```

Theese messages are produced by some built-in validator with [this code](https://github.com/metio/terraform-provider-migadu/blob/main/internal/provider/identity_resource.go#L196-L203). The docs for `Any` say:

> To prevent practitioner confusion should non-passing validators have conflicting logic, only warnings from the passing validator are returned. Use AnyWithAllWarnings() to return warnings from non-passing validators as well.

Since there is no passing validator terraform/tofu prints messages from both validators. So writing a custom validator is the only choice here to produce a custom message. I'll give it a shot & let you know how it goes ^^

**Comment by ajgon** [comment]
This message is only quality of life improvement, if it requires some major refactoring I think it's not worth it (unless you want to do it, obviously :) ). After I found out what's wrong, it become pretty clear :)

**Comment by sebhoss** [comment]
Sorry for the delay here - the next release will include a custom validator that should produce less confusing output. Releases happen automatically on thursday so that should be 2024-02-22.

Thanks again for taking your time to improve this provider. It's always highly appreciated ^^
