### ISSUE TITLE
feature: Domain Aliases

### ISSUE THREAD

**Issue by mircea-pavel-anton** [metio/terraform-provider-migadu#230]
I would like to configure domain aliases in migadu using this provider, but this resource is currently not available

**Comment by sebhoss** [comment]
Thanks! I did not realize they added new API endpoints. Plan of action here is to extend the migadu-client lib (https://github.com/metio/migadu-client.go) and add terraform data sources as well as resources based on that to this provider.

**Comment by mircea-pavel-anton** [comment]
@sebhoss oh, I just checked and you are right... Domain aliases are not exposed via their API. 😅
 
I'll try a support ticket with them and see what luck I have.

In the meantime, I think we can close this issue.

Thanks for the fast response. Happy holidays!
