### ISSUE TITLE
Value conversion error on terraform plan

### ISSUE THREAD

**Issue by mapperr** [metio/terraform-provider-migadu#26]
Hi!

I just catched this behaviour:

```
Error: Value Conversion Error
│
│   with migadu_mailbox.extra_emails["mymail"],
│   on emails.tf line 55, in resource "migadu_mailbox" "extra_emails":
│   55: resource "migadu_mailbox" "extra_emails" {
│
│ An unexpected error was encountered trying to convert the Terraform value.
│ This is always an error in the provider. Please report the following to the
│ provider developer:
│
│ Value %!s(*big.Float=0.01) cannot be represented as a 64-bit floating
│ point.
```

That "0.01" is the GB usage of "mymail" mailbox I just imported with `terraform import migadu_mailbox.extra_emails["mymail"] mymail@mydomain.com`.

I'm using terraform 1.3.9

I think it's probably caused by a bug in the terraform-plugin-framework:
https://github.com/hashicorp/terraform-plugin-framework/issues/647

If that is the problem, then the terraform guys have fixed the bug in the 1.2.0 release,
so maybe a bump of terraform-plugin-framework to 1.2.0 should fix this too (hopefully)!

Thank you for this provider : )

**Comment by sebhoss** [comment]
aargh yeah I was afraid that something like that was going to happen. I'm not entirely sure whether the current usage of a mailbox is even useful and I only added it because the API exposes that information. So I thinking that removing that field entirely would eliminate that problem now without waiting for a potential fix in the provider framework - WDYT? Are you using this info somewhere?

In any case, thanks for creating this ticket and providing all that useful information!

**Comment by mapperr** [comment]
> aargh yeah I was afraid that something like that was going to happen. I'm not entirely sure whether the current usage of a mailbox is even useful and I only added it because the API exposes that information. So I thinking that removing that field entirely would eliminate that problem now without waiting for a potential fix in the provider framework - WDYT? Are you using this info somewhere?

Nah, I'm not using it anywhere, and I think you are right, I doubt it can be useful in the terraform context.
I see it as a somewhat volatile info useful for, idk, monitoring? ¯\\_(ツ)_/¯

I think you can remove it without worries.

> In any case, thanks for creating this ticket and providing all that useful information!

No problem, thank you for the provider ^^

**Comment by sebhoss** [comment]
OK thanks again ^^

I'm doing [automated releases](https://github.com/metio/terraform-provider-migadu/blob/main/.github/workflows/release.yml#L7) in this repo and the next one would be on Wednesday (2023-03-01)

**Comment by mapperr** [comment]
Perfect: updated provider version to [2023.3.1](https://github.com/metio/terraform-provider-migadu/releases/tag/2023.3.1), re-added the problematic email address, worked like a charm.

Thanks!

**Comment by sebhoss** [comment]
Ah thanks for the feedback - was about to ping you that the release happened, but had a busy day...
