### ISSUE TITLE
Provider returned invalid result object after apply

### ISSUE THREAD

**Issue by sorvis** [metio/terraform-provider-migadu#75]
```
│ Error: Provider returned invalid result object after apply
│ 
│ After the apply operation, the provider still indicated an unknown value for
│ migadu_mailbox.mailbox.password. All values must be known after apply, so
│ this is always a bug in the provider and should be reported in the provider's
│ own repository. Terraform will still save the other known object values in
│ the state.

```

**Comment by sebhoss** [comment]
Thanks for reaching out! This should be fixed with the referenced commit which will be part of the next released scheduled for 2023-07-12

**Comment by sebhoss** [comment]
hey @sorvis this should be fixed now with https://github.com/metio/terraform-provider-migadu/releases/tag/2023.7.12 which is already up in the Terraform registry. https://registry.terraform.io/providers/metio/migadu/latest/docs/resources/mailbox#example-usage contains an example that shows the invitation flow
